projectile.max-loads-per-projectile:
- expressions:
  - parseInt(pufferfish["projectile"]["max-load-per-projectile"]) >= 9
  prefix: "❌"
  value: "Decrease this in pufferfish.yml.<br>Recommended: 8."
dab.enabled:
- expressions:
  - pufferfish["dab"]["enabled"] == "false"
  prefix: "❌"
  value: "Enable this in pufferfish.yml."